matrix_chain_begin();
matrix_chain_rotate_x( -90 );
matrix_chain_rotate_z( image_angle );
if ( global.game_room == 6 ) matrix_chain_scale( 1, 1, -1 );
matrix_chain_translate( x, y, z );
if ( global.game_room != 6 ) matrix_chain_translate( 0, 0, global.game_swell );
if ( global.game_room == 6 ) matrix_chain_translate( 0, 0, -global.game_swell );
matrix_chain_end( matrix_world );
dotobj_submit( "phonebase" );
dotobj_submit( "phonerotary" );

matrix_chain_begin();
matrix_chain_rotate_x( -90 );
matrix_chain_rotate_y( 45*headset_t );
matrix_chain_translate( 0, -5, 5 );
matrix_chain_rotate_x( 80*headset_t );
matrix_chain_translate( 0, 5, -5 );
matrix_chain_translate( 7*headset_t, -2*headset_t, 8*headset_t );
matrix_chain_rotate_z( image_angle );
if ( global.game_room == 6 ) matrix_chain_scale( 1, 1, -1 );
matrix_chain_translate( x, y, z );
if ( global.game_room != 6 ) matrix_chain_translate( 0, 0, global.game_swell );
if ( global.game_room == 6 ) matrix_chain_translate( 0, 0, -global.game_swell );
matrix_chain_end( matrix_world );
dotobj_submit( "phoneheadset" );
matrix_reset_world();