/// @description TRACKER service internal definitions

#macro TRACKER_PROTECTED_LABEL "P"
#macro TRACKER_VOLATILE_LABEL "_"
enum E_TRACKER_PAGE { HOME, OUTPUT, GRIPS, SURFACE_PREVIEW, MAPS, LISTS, GRIDS, SURFACES, VERTEX_BUFFERS, INSTANCES }